const SUPABASE_URL="https://gfvwuzbwmvafcukadupo.supabase.co";
const SUPABASE_KEY="sb_publishable_dtc_AGtoapQyLTZe2TZ14Q_K3-21oSA";
const APP_URL="https://fabpa001.github.io/VICOLO-CECHOV-SALE/";
let authUrlSnapshot=(window.location.hash||"")+" "+(window.location.search||"");
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentUser=null,currentProfile=null;
let groups=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let bookings=[],news=[],holidayPeriods=[],cursor=new Date(),bookingsChannel=null,notificationsChannel=null;
async function loadHolidayPeriods(){let {data,error}=await db.from("holiday_periods").select("id,start_date,end_date").order("start_date");if(error){console.error(error);return}holidayPeriods=data||[];renderHolidayPeriods()}
function renderHolidayPeriods(){let box=$("#holidayList");if(!box)return;box.innerHTML=holidayPeriods.length?holidayPeriods.map(h=>'<div class="item"><b>DAL '+new Date(h.start_date+"T12:00").toLocaleDateString("it-IT")+' AL '+new Date(h.end_date+"T12:00").toLocaleDateString("it-IT")+'</b><button class="reject" data-holiday-del="'+h.id+'">🗑 Elimina</button></div>').join(""):'<div class="muted">Nessun periodo inserito.</div>';$("[data-holiday-del]").forEach(x=>x.onclick=async()=>{if(!confirm("Eliminare questo periodo di festività?"))return;let {error}=await db.from("holiday_periods").delete().eq("id",x.dataset.holidayDel);if(error){alert(bookingError(error));return}await loadHolidayPeriods()})}
function isHolidayDate(date){return holidayPeriods.some(h=>date>=h.start_date&&date<=h.end_date)}
async function loadNotifications(){if(!currentUser)return;let {data,error}=await db.from("notifications").select("id,booking_id,kind,title,message,is_read,created_at").order("created_at",{ascending:false}).limit(100);if(error){console.error(error);return}news=(data||[]).map(n=>({id:n.id,text:n.title+" — "+n.message,at:n.created_at,read:n.is_read}));renderNews();badge()}
function subscribeNotifications(){if(notificationsChannel){db.removeChannel(notificationsChannel);notificationsChannel=null}notificationsChannel=db.channel("user-notifications-"+currentUser.id).on("postgres_changes",{event:"*",schema:"public",table:"notifications",filter:"user_id=eq."+currentUser.id},()=>loadNotifications()).subscribe(status=>{if(status==="SUBSCRIBED")loadNotifications()})}
const timeHM=t=>String(t||"").slice(0,5);
const fromDbBooking=b=>({id:b.id,seriesId:b.series_id||null,room:b.room_preference==="any"?"Una qualsiasi":b.room,date:b.booking_date,start:timeHM(b.start_time),end:timeHM(b.end_time),group:b.activity,note:b.note||"",actor:b.actor_name||"Utente",status:b.status,requestedBy:b.requested_by});
async function loadBookings(){let {data,error}=await db.from("bookings").select("id,series_id,booking_date,start_time,end_time,room,room_preference,activity,note,status,requested_by,actor_name").neq("status","cancelled").order("booking_date",{ascending:true}).order("start_time",{ascending:true});if(error){console.error(error);return false}bookings=(data||[]).map(fromDbBooking);renderAll();return true}
let bookingRefreshTimer=null;
function scheduleBookingRefresh(){clearTimeout(bookingRefreshTimer);bookingRefreshTimer=setTimeout(()=>loadBookings(),150)}
function subscribeBookings(){if(bookingsChannel){db.removeChannel(bookingsChannel);bookingsChannel=null}bookingsChannel=db.channel("shared-bookings-"+currentUser.id).on("postgres_changes",{event:"*",schema:"public",table:"bookings"},scheduleBookingRefresh).subscribe(status=>{console.log("Realtime bookings:",status);if(status==="SUBSCRIBED")loadBookings()})}
window.addEventListener("focus",()=>{if(currentUser)loadBookings()});
document.addEventListener("visibilitychange",()=>{if(!document.hidden&&currentUser)loadBookings()});
function bookingError(error){let m=error&&error.message?error.message:"Errore durante il salvataggio.";if(m.includes("BOOKING_CONFLICT")||m.includes("no_approved_room_overlap"))return "La sala risulta già occupata in questa fascia.";if(m.includes("ROOM_REQUIRED")||m.includes("ADMIN_ROOM_REQUIRED"))return "Devi scegliere una sala precisa.";if(m.includes("ADMIN_ONLY"))return "Questa operazione è riservata agli amministratori.";return m}
const iso=d=>{let x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}, mins=t=>{let[a,b]=t.split(":").map(Number);return a*60+b}, overlap=(a,b,c,d)=>mins(a)<mins(d)&&mins(c)<mins(b), fmt=d=>new Date(d+"T12:00").toLocaleDateString("it-IT",{weekday:"long",day:"numeric",month:"long"});
function renderConsultGroups(){if(!$("#consultGroup"))return;let names=[...new Set([...groups.map(g=>g.name),...bookings.map(b=>b.group)].filter(Boolean))].sort((a,b)=>a.localeCompare(b,"it",{sensitivity:"base",numeric:true}));$("#consultGroup").innerHTML=names.map(n=>"<option>"+esc(n)+"</option>").join("")}
function renderConsult(){let group=$("#consultGroup").value,from=$("#consultFrom").value,to=$("#consultTo").value;if(!group){$("#consultResult").innerHTML='<div class="card">Nessun gruppo disponibile.</div>';return}let rows=bookings.filter(b=>b.group===group&&b.status!=="cancelled"&&(!from||b.date>=from)&&(!to||b.date<=to)).sort((a,b)=>a.date.localeCompare(b.date)||a.start.localeCompare(b.start));let title='<div class="card"><h2>'+esc(group)+'</h2><b>Totale prenotazioni: '+rows.length+'</b>'+(from||to?'<div class="muted smallpad">'+(from?'Dal '+new Date(from+"T12:00").toLocaleDateString("it-IT"):'')+(from&&to?' · ':'')+(to?'Al '+new Date(to+"T12:00").toLocaleDateString("it-IT"):'')+'</div>':'')+'</div>';let list=rows.map(b=>'<div class="card"><b>'+new Date(b.date+"T12:00").toLocaleDateString("it-IT")+'</b><br>'+esc(b.start)+'–'+esc(b.end)+' · '+(b.room==="Grande"?'🟠 Sala Grande':b.room==="Piccola"?'🟣 Sala Piccola':esc(b.room||"Sala da assegnare"))+(b.status==="pending"?' · IN ATTESA':'')+'</div>').join("");$("#consultResult").innerHTML=title+(list||'<div class="card muted">Nessuna prenotazione nel periodo selezionato.</div>')}
function go(id){$(".view").forEach(v=>v.classList.remove("active"));$("#"+id).classList.add("active");if(id==="requests")renderRequests();if(id==="news")renderNews();if(id==="consult"){renderConsultGroups();renderConsult()}window.scrollTo(0,0)}
$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go)); $("#bell").onclick=()=>go("news");
$("#consultBtn").onclick=renderConsult;$("#consultGroup").onchange=renderConsult;$("#consultFrom").onchange=renderConsult;$("#consultTo").onchange=renderConsult;$("#group").onchange=e=>$("#otherWrap").hidden=e.target.value!=="ALTRO";$("#repeat").onchange=e=>$("#untilWrap").hidden=!e.target.checked;
function groupSort(a,b){return a.name.localeCompare(b.name,"it",{sensitivity:"base",numeric:true})}
function renderGroupSelect(){let active=groups.filter(g=>g.active).sort(groupSort);$("#group").innerHTML=active.map(g=>"<option>"+g.name+"</option>").join("")+"<option>ALTRO</option>";$("#otherWrap").hidden=$("#group").value!=="ALTRO"}
async function loadGroups(){let {data,error}=await db.from("groups").select("id,name,active,created_at").order("name",{ascending:true});if(error){console.error(error);return}groups=data||[];renderGroupSelect();if(currentProfile&&currentProfile.role==="admin")renderGroupAdmin()}
function renderGroupAdmin(){if(!currentProfile||currentProfile.role!=="admin")return;let active=groups.filter(g=>g.active).sort(groupSort);$("#groupAdminList").innerHTML=active.length?active.map(g=>'<div class="groupadminitem"><b>'+g.name+'</b><button class="reject" data-group-disable="'+g.id+'">Rimuovi</button></div>').join(""):'<div class="muted smallpad">Nessun gruppo attivo.</div>';$$("[data-group-disable]").forEach(b=>b.onclick=()=>disableGroup(b.dataset.groupDisable))}
async function addGroup(){let name=$("#newGroupName").value.trim();if(!name){$("#groupAdminMsg").textContent="Inserisci il nome del gruppo.";return}let existing=groups.find(g=>g.name.localeCompare(name,"it",{sensitivity:"base"})===0);if(existing){if(existing.active){$("#groupAdminMsg").textContent="Questo gruppo esiste già.";return}let {error}=await db.from("groups").update({active:true}).eq("id",existing.id);if(error){$("#groupAdminMsg").textContent=error.message;return}$("#groupAdminMsg").textContent="Gruppo riattivato.";$("#newGroupName").value="";await loadGroups();return}let {error}=await db.from("groups").insert({name,active:true,created_by:currentUser.id});if(error){$("#groupAdminMsg").textContent=error.message;return}$("#newGroupName").value="";$("#groupAdminMsg").textContent="Gruppo aggiunto.";await loadGroups()}
async function disableGroup(id){let g=groups.find(x=>x.id===id);if(!g)return;let today=iso(new Date());let related=bookings.filter(b=>b.group===g.name&&b.date>=today&&b.status!=="rejected");if(!related.length){if(!confirm('Rimuovere "'+g.name+'" dall’elenco dei gruppi?'))return;await finishGroupRemoval(g,false);return}$("#groupBookingChoiceTitle").textContent='Rimuovi "'+g.name+'"';$("#groupBookingChoiceText").textContent="Ci sono "+related.length+" prenotazioni future per questo gruppo. Vuoi cancellarle insieme al gruppo?";$("#groupBookingChoice").hidden=false;$("#removeGroupAndBookings").onclick=async()=>{await finishGroupRemoval(g,true);$("#groupBookingChoice").hidden=true};$("#removeGroupKeepBookings").onclick=async()=>{await finishGroupRemoval(g,false);$("#groupBookingChoice").hidden=true};$("#cancelGroupRemoval").onclick=()=>$("#groupBookingChoice").hidden=true} async function finishGroupRemoval(g,alsoBookings){let {error}=await db.from("groups").update({active:false}).eq("id",g.id);if(error){$("#groupAdminMsg").textContent=error.message;return}if(alsoBookings){let today=iso(new Date()),ids=bookings.filter(b=>b.group===g.name&&b.date>=today&&b.status!=="rejected").map(b=>b.id);if(ids.length){let {error:delError}=await db.from("bookings").delete().in("id",ids);if(delError){$("#groupAdminMsg").textContent=bookingError(delError);return}}$("#groupAdminMsg").textContent="Gruppo rimosso e prenotazioni future cancellate."}else{$("#groupAdminMsg").textContent="Gruppo rimosso. Le prenotazioni esistenti restano nel calendario."}await loadGroups();await loadBookings()}
function roomAvailability(){let date=$("#date").value,start=$("#start").value,end=$("#end").value,box=$("#roomChoices"),hint=$("#availabilityHint");if(!date||!start||!end||mins(end)<=mins(start)){box.innerHTML="";hint.textContent="Inserisci una data e una fascia oraria valida.";$("#room").value="";return}let rooms=["Sala Grande","Sala Piccola"],free=rooms.filter(r=>!bookings.some(b=>b.date===date&&b.room===r&&["approved","pending"].includes(b.status)&&overlap(b.start,b.end,start,end)));let choices=[];for(let r of rooms){let ok=free.includes(r);choices.push(`<button type="button" class="roomchoice ${ok?"free":"busy"}" data-room="${r}" ${ok?"":"disabled"}><b>${r.includes("Grande")?"🟠":"🟣"} ${r}</b><span>${ok?"LIBERA":"OCCUPATA / RICHIESTA"}</span></button>`)}if(free.length===2&&currentProfile&&currentProfile.role!=="admin")choices.push(`<button type="button" class="roomchoice any" data-room="Una qualsiasi"><b>🎭 Una qualsiasi</b><span>Deciderà l’admin</span></button>`);box.innerHTML=choices.join("");hint.textContent=free.length?free.length===2?"Entrambe le sale sono disponibili.":"È disponibile una sola sala.":"Nessuna sala disponibile in questa fascia.";$("#room").value="";$$("[data-room]").forEach(b=>b.onclick=()=>{$$(".roomchoice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("#room").value=b.dataset.room})}
$("#date").addEventListener("change",roomAvailability);$("#start").addEventListener("change",roomAvailability);$("#end").addEventListener("change",roomAvailability);
function addNews(text){console.log("Admin activity:",text)}
function roomClass(r){return r==="Una qualsiasi"?"any":r.includes("Grande")?"grande":"piccola"} function dotClass(r){return r==="Una qualsiasi"?"any":r.includes("Grande")?"orange":"purple"}
function renderHome(){let t=iso(new Date());$("#todayDate").textContent=fmt(t);let arr=bookings.filter(b=>b.date===t&&b.status==="approved").sort((a,b)=>a.start.localeCompare(b.start));$("#todayRooms").innerHTML=["Sala Grande","Sala Piccola"].map(r=>{let a=arr.filter(b=>b.room===r);return '<div class="card roomline '+roomClass(r)+'"><b>'+r+'</b>'+(a.length?a.map(b=>'<div>'+b.start+'–'+b.end+' · '+b.group+(b.note?' — '+b.note:'')+'</div>').join(""):'<div class="muted">Libera oggi</div>')+'</div>'}).join("")}
function renderCalendar(){let y=cursor.getFullYear(),m=cursor.getMonth();$("#monthTitle").textContent=new Date(y,m,1).toLocaleDateString("it-IT",{month:"long",year:"numeric"});let first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),html="";for(let i=0;i<first;i++)html+='<div class="daycell empty"></div>';for(let d=1;d<=days;d++){let date=iso(new Date(y,m,d)),arr=bookings.filter(b=>b.date===date&&["approved","pending"].includes(b.status));let dots=arr.map(b=>'<i class="dot '+dotClass(b.room)+' '+(b.status==="pending"?"pending":"")+'"></i>').join("");html+='<div class="daycell" data-date="'+date+'"><div class="daynum">'+d+'</div><div class="dots">'+dots+'</div></div>'}$("#monthGrid").innerHTML=html;$$(".daycell[data-date]").forEach(x=>x.onclick=()=>renderDay(x.dataset.date))}
function renderDay(date){go("day");$("#dayTitle").textContent=fmt(date);let a=bookings.filter(b=>b.date===date&&b.status!=="rejected").sort((x,y)=>x.start.localeCompare(y.start));$("#dayList").innerHTML=a.length?a.map(b=>'<div class="item roomline '+roomClass(b.room)+'"><b>'+b.start+'–'+b.end+' · '+b.room+'</b><div>'+b.group+'</div><small>'+b.actor+(b.note?' · '+b.note:'')+'</small><div><span class="tag '+(b.status==="pending"?"pending":"ok")+'">'+(b.status==="pending"?"IN ATTESA":"CONFERMATA")+'</span></div>'+(currentProfile&&currentProfile.role==="admin"?'<div class="actions"><button class="reject" data-del="'+b.id+'">🗑 Cancella'+(b.seriesId?' / serie':'')+'</button></div>':'')+'</div>').join(""):'<div class="card muted">Nessuna prenotazione.</div>';$$("[data-del]").forEach(x=>x.onclick=()=>deleteBooking(x.dataset.del))}
async function deleteBooking(id){let b=bookings.find(x=>x.id===id);if(!b)return;if(b.seriesId){openSeriesDelete(b);return}if(!confirm("Vuoi cancellare questa prenotazione?"))return;let {error}=await db.from("bookings").delete().eq("id",id);if(error){alert(bookingError(error));return}addNews("Prenotazione cancellata: "+b.group+" · "+fmt(b.date)+" "+b.start+"–"+b.end);await loadBookings();go("calendar")}
function openSeriesDelete(b){$("#seriesDeleteText").textContent=b.group+" · "+fmt(b.date)+" · "+b.start+"–"+b.end;$("#seriesDeleteModal").hidden=false;$("#deleteOne").onclick=async()=>{let {error}=await db.from("bookings").delete().eq("id",b.id);if(error){alert(bookingError(error));return}addNews("Data cancellata dalla serie: "+b.group+" · "+fmt(b.date));closeSeriesDelete();await loadBookings();go("calendar")};$("#deleteSeries").onclick=async()=>{let {error}=await db.from("bookings").delete().eq("series_id",b.seriesId);if(error){alert(bookingError(error));return}addNews("Serie cancellata: "+b.group+" · "+b.room);closeSeriesDelete();await loadBookings();go("calendar")}}
function closeSeriesDelete(){$("#seriesDeleteModal").hidden=true}
$("#deleteCancel").onclick=closeSeriesDelete;
function renderRequests(){let a=bookings.filter(b=>b.status==="pending").sort((x,y)=>(x.date+x.start).localeCompare(y.date+y.start));let admin=currentProfile&&currentProfile.role==="admin";$("#requestList").innerHTML=a.length?a.map(b=>'<div class="item"><b>'+fmt(b.date)+'</b><div>'+b.start+'–'+b.end+' · '+b.room+'</div><div>'+b.group+'</div><small>Richiesta da '+b.actor+(b.note?' · '+b.note:'')+'</small>'+(admin?'<div class="actions"><button class="approve" data-a="'+b.id+'">✓ Approva</button><button class="reject" data-r="'+b.id+'">✕ Rifiuta</button></div>':'')+'</div>').join(""):'<div class="card muted">Nessuna richiesta in attesa.</div>';$$("[data-a]").forEach(x=>x.onclick=()=>approve(x.dataset.a));$$("[data-r]").forEach(x=>x.onclick=()=>reject(x.dataset.r))}
function chooseApprovalRoom(){return new Promise(resolve=>{let m=$("#roomApprovalModal");m.hidden=false;let done=v=>{m.hidden=true;$("#approveGrande").onclick=null;$("#approvePiccola").onclick=null;$("#approveRoomCancel").onclick=null;resolve(v)};$("#approveGrande").onclick=()=>done("Sala Grande");$("#approvePiccola").onclick=()=>done("Sala Piccola");$("#approveRoomCancel").onclick=()=>done(null)})}
async function approve(id){let b=bookings.find(x=>x.id===id);if(!b)return;let chosen=null;if(b.room==="Una qualsiasi"){let free=["Sala Grande","Sala Piccola"].filter(r=>!bookings.some(x=>x.id!==id&&x.date===b.date&&x.room===r&&["approved","pending"].includes(x.status)&&overlap(x.start,x.end,b.start,b.end)));if(!free.length){alert("Nessuna sala è disponibile in questa fascia.");return}chosen=free.length===1?free[0]:await chooseApprovalRoom();if(!chosen)return}let {error}=await db.rpc("approve_booking",{p_booking_id:id,p_room:chosen});if(error){alert(bookingError(error));return}let assigned=chosen||b.room;let {error:nerr}=await db.from("notifications").insert({user_id:b.requestedBy,booking_id:id,kind:"approved",title:"✅ RICHIESTA APPROVATA",message:b.group+" · "+fmt(b.date)+" · "+b.start+"–"+b.end+" · "+assigned});if(nerr)console.error("Notifica:",nerr);await loadBookings();alert("Richiesta approvata.")}
async function reject(id){let b=bookings.find(x=>x.id===id);if(!b)return;let {error}=await db.from("bookings").update({status:"rejected"}).eq("id",id);if(error){alert(bookingError(error));return}let {error:nerr}=await db.from("notifications").insert({user_id:b.requestedBy,booking_id:id,kind:"rejected",title:"❌ RICHIESTA NON APPROVATA",message:b.group+" · "+fmt(b.date)+" · "+b.start+"–"+b.end});if(nerr)console.error("Notifica:",nerr);await loadBookings();alert("Richiesta non approvata.")}
function renderNews(){let a=news;$("#newsList").innerHTML=a.length?a.map(n=>'<div class="item">'+(!n.read?'<b>● NOVITÀ</b> ':'')+n.text+'<br><small>'+new Date(n.at).toLocaleString("it-IT")+'</small></div>').join(""):'<div class="card muted">Nessuna novità.</div>'}
$("#readAll").onclick=async()=>{let {error}=await db.from("notifications").update({is_read:true}).eq("user_id",currentUser.id).eq("is_read",false);if(error){console.error(error);return}await loadNotifications()};function badge(){let n=news.filter(x=>!x.read).length;$("#badge").textContent=n;$("#badge").dataset.zero=n?"0":"1"}
function confirmRecurringConflicts(conf){return new Promise(resolve=>{let m=$("#recurringConflictModal"),list=$("#recurringConflictList");list.innerHTML=conf.map(d=>"<div><b>• "+fmt(d)+"</b></div>").join("");m.hidden=false;let done=v=>{m.hidden=true;$("#continueRecurring").onclick=null;$("#cancelRecurring").onclick=null;resolve(v)};$("#continueRecurring").onclick=()=>done(true);$("#cancelRecurring").onclick=()=>done(false)})}
$("#addHolidayBtn").onclick=async()=>{let a=$("#holidayFrom").value,b=$("#holidayTo").value;if(!a||!b||b<a){$("#holidayMsg").textContent="Controlla le date.";return}let {error}=await db.from("holiday_periods").insert({start_date:a,end_date:b});if(error){$("#holidayMsg").textContent=bookingError(error);return}$("#holidayFrom").value="";$("#holidayTo").value="";$("#holidayMsg").textContent="Periodo aggiunto.";await loadHolidayPeriods()};
$("#bookForm").onsubmit=async e=>{e.preventDefault();let role=currentProfile.role,room=$("#room").value,date=$("#date").value,start=$("#start").value,end=$("#end").value,group=$("#group").value==="ALTRO"?($("#other").value.trim()||"ALTRO"):$("#group").value,note=$("#note").value.trim();if(!date||mins(end)<=mins(start)){alert("Controlla data e orari.");return}if(!room){alert("Scegli una delle sale disponibili.");return}if(role==="admin"&&room==="Una qualsiasi"){alert("Come ADMIN devi scegliere una sala precisa.");return}let recurring=$("#repeat").checked,until=$("#until").value;if(recurring&&role!=="admin"){alert("Le prenotazioni ricorrenti sono gestite dagli admin.");return}let dates=[date];if(recurring){if(!until||until<date){alert("Inserisci la data finale.");return}let d=new Date(date+"T12:00"),u=new Date(until+"T12:00");while((d=new Date(d.getTime()+7*86400000))<=u)dates.push(iso(d));if($("#excludeHolidays").checked)dates=dates.filter(dt=>!isHolidayDate(dt));if(!dates.length){alert("Tutte le date della serie rientrano nei periodi di festività.");return}}let seriesId=recurring?crypto.randomUUID():null,made=0,conf=[];
if(recurring){conf=dates.filter(dt=>bookings.some(b=>b.date===dt&&b.room===room&&["approved","pending"].includes(b.status)&&overlap(b.start,b.end,start,end)));if(conf.length){let proceed=await confirmRecurringConflicts(conf);if(!proceed){$("#bookMsg").innerHTML='<div class="card"><b>Prenotazione annullata</b><div>Nessuna data della serie è stata inserita.</div></div>';return}}}
for(let dt of dates){if(recurring&&conf.includes(dt))continue;let {error}=await db.rpc("create_booking",{p_booking_date:dt,p_start_time:start,p_end_time:end,p_room:room==="Una qualsiasi"?null:room,p_room_preference:room==="Una qualsiasi"?"any":"specific",p_activity:group,p_note:note||null,p_series_id:seriesId});if(error){if(bookingError(error).includes("già occupata")){conf.push(dt);continue}alert(bookingError(error));break}made++}await loadBookings();if(made){let actor=currentProfile.display_name||currentUser.email;if(role!=="admin")addNews("Nuova richiesta di "+actor+": "+room+" · "+fmt(date)+" "+start+"–"+end);else addNews("Nuova prenotazione: "+group+" · "+room+" · "+fmt(date)+" "+start+"–"+end)}let resultTitle=recurring?(conf.length?"⚠️ Serie inserita con conflitti":"Serie inserita"):(role==="admin"?"Prenotazione registrata":"Richiesta inviata");let resultDetail=made+" data/e aggiunte"+(conf.length?" · "+conf.length+" conflitto/i saltato/i: "+conf.map(fmt).join(", "):"")+".";
$("#bookMsg").innerHTML='<div class="card"><b>'+resultTitle+'</b><div>'+resultDetail+'</div></div>';

go(role==="admin"?"calendar":"requests")};
$("#prevMonth").onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);renderCalendar()};$("#nextMonth").onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);renderCalendar()};
function renderAll(){renderHome();renderCalendar();renderRequests();badge();roomAvailability()}
async function enterApp(user){currentUser=user;let {data,error}=await db.from("profiles").select("id,display_name,role").eq("id",user.id).single();if(error||!data){$("#authMsg").textContent="Profilo non ancora disponibile. Riprova tra qualche secondo.";return}currentProfile=data;$("#authScreen").hidden=true;$("#appShell").hidden=false;$("#currentUser").textContent=(data.display_name||user.email)+" · "+(data.role==="admin"?"ADMIN":"OPERATORE");$("#roleInfo").innerHTML=data.role==="admin"?"Sei ADMIN: puoi inserire prenotazioni dirette e ricorrenti.":"Sei OPERATORE: le prenotazioni singole vengono inviate come richieste.";$("#repeat").closest("label").style.display=data.role==="admin"?"flex":"none";$("#holidayAdminCard").hidden=data.role!=="admin";$("#adminAccessCard").hidden=data.role!=="admin";$("#adminGroupsCard").hidden=data.role!=="admin";if(data.role!=="admin"){$("#repeat").checked=false;$("#untilWrap").hidden=true}else{await renderInvites()}$("#date").value=iso(new Date());await loadGroups();await loadBookings();await loadHolidayPeriods();await loadNotifications();subscribeBookings();subscribeNotifications();renderAll()}
function showAuth(msg=""){$("#appShell").hidden=true;$("#authScreen").hidden=false;$("#authMsg").textContent=msg}
function setAuthMode(mode){$("#loginMode").hidden=mode!=="login";$("#forgotMode").hidden=mode!=="forgot";$("#resetErrorMode").hidden=mode!=="resetError";$("#resetSentMode").hidden=mode!=="resetSent";$("#signupMode").hidden=mode!=="signup";$("#inviteMode").hidden=mode!=="invite";$("#activationSuccessMode").hidden=mode!=="activationSuccess";$("#recoveryMode").hidden=mode!=="recovery";$("#authMsg").textContent=""}
async function login(){let email=$("#authEmail").value.trim(),password=$("#authPassword").value;if(!email||!password){showAuth("Inserisci email e password.");return}$("#authMsg").textContent="Accesso...";let {data,error}=await db.auth.signInWithPassword({email,password});if(error){showAuth(error.message);return}await enterApp(data.user)}
async function signup(){let name=$("#authName").value.trim(),email=$("#signupEmail").value.trim().toLowerCase(),password=$("#signupPassword").value;if(!name||!email||password.length<6){$("#authMsg").textContent="Inserisci nome, email e una password di almeno 6 caratteri.";return}$("#authMsg").textContent="Creazione account...";let {data,error}=await db.auth.signUp({email,password,options:{data:{name},emailRedirectTo:APP_URL}});if(error){$("#authMsg").textContent=error.message.includes("Database error")?"Questa email non è stata ancora autorizzata da un amministratore.":error.message;return}if(data.session&&data.user){await enterApp(data.user)}else{$("#authMsg").textContent="Account creato. Controlla la tua email e conferma l'indirizzo, poi torna qui e accedi.";setAuthMode("login")}}
async function prepareInviteMode(session){if(!session||!session.user)return;let email=session.user.email||"";$("#inviteAccountEmail").textContent=email;let n=session.user.user_metadata&&session.user.user_metadata.name?String(session.user.user_metadata.name):"";if(n&&!$("#inviteName").value)$("#inviteName").value=n}
async function completeInvite(){let name=$("#inviteName").value.trim(),p1=$("#invitePassword").value,p2=$("#invitePassword2").value,btn=$("#completeInviteBtn");if(name.length<2){$("#authMsg").textContent="Inserisci il tuo nome.";return}if(p1.length<6){$("#authMsg").textContent="La password deve avere almeno 6 caratteri.";return}if(p1!==p2){$("#authMsg").textContent="Le due password non coincidono.";return}btn.disabled=true;btn.textContent="Attivazione…";$("#authMsg").textContent="";let {data:{session}}=await db.auth.getSession();if(!session||!session.user){btn.disabled=false;btn.textContent="Attiva account";$("#authMsg").textContent="Il link di invito non è più valido. Chiedi all’amministratore un nuovo invito.";return}let email=session.user.email||"";let {error:userError}=await db.auth.updateUser({password:p1,data:{name}});if(userError){btn.disabled=false;btn.textContent="Attiva account";$("#authMsg").textContent=userError.message;return}let {error:profileError}=await db.rpc("complete_invited_profile",{p_display_name:name});if(profileError){btn.disabled=false;btn.textContent="Attiva account";$("#authMsg").textContent="La password è stata salvata, ma non siamo riusciti a completare il profilo. Riprova.";return}$("#authEmail").value=email;$("#activationEmail").textContent=email;inviteFlow=false;authUrlSnapshot="";history.replaceState(null,"",window.location.pathname);await db.auth.signOut();btn.disabled=false;btn.textContent="Attiva account";setAuthMode("activationSuccess")}
async function forgotPassword(){let email=$("#resetEmail").value.trim().toLowerCase(),btn=$("#sendResetBtn");if(!email){$("#authMsg").textContent="Inserisci la tua email.";$("#resetEmail").focus();return}btn.disabled=true;btn.textContent="Invio in corso…";$("#authMsg").textContent="";let {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:APP_URL});btn.disabled=false;btn.textContent="Invia email di recupero";if(error){let msg=(error.message||"").toLowerCase();$("#resetErrorText").textContent=msg.includes("rate limit")?"Hai richiesto più email in poco tempo. Attendi circa 5 minuti e poi riprova.":"Non è stato possibile inviare l’email di recupero. Attendi qualche minuto e riprova.";setAuthMode("resetError");return}$("#resetSentEmail").textContent=email;setAuthMode("resetSent")}
async function saveNewPassword(){let p1=$("#newPassword").value,p2=$("#newPassword2").value;if(p1.length<6){$("#authMsg").textContent="La password deve avere almeno 6 caratteri.";return}if(p1!==p2){$("#authMsg").textContent="Le due password non coincidono.";return}$("#authMsg").textContent="Salvataggio...";let {error}=await db.auth.updateUser({password:p1});if(error){$("#authMsg").textContent=error.message;return}$("#authMsg").textContent="Password aggiornata. Ora puoi accedere.";history.replaceState(null,"",window.location.pathname);recoveryFlow=false;authUrlSnapshot="";await db.auth.signOut();setAuthMode("login")}
async function renderInvites(){if(!currentProfile||currentProfile.role!=="admin")return;let {data,error}=await db.from("invitations").select("id,email,role,used_at,activated_at,created_at").order("created_at",{ascending:false});if(error){$("#inviteList").innerHTML='<div class="muted smallpad">Impossibile caricare gli inviti.</div>';return}$("#inviteList").innerHTML=(data||[]).map(i=>'<div class="inviteitem"><b>'+i.email+'</b><span>'+(i.role==="admin"?"ADMIN":"OPERATORE")+(i.activated_at?" · ATTIVATO":" · INVITO INVIATO")+'</span></div>').join("")||'<div class="muted smallpad">Nessun invito inviato.</div>'}
async function edgeErrorMessage(error){try{if(error&&error.context&&typeof error.context.clone==="function"){let body=await error.context.clone().json();if(body&&body.error)return body.error}}catch{}return error&&error.message?error.message:"Non è stato possibile inviare l’invito."}
async function authorizeEmail(){let email=$("#inviteEmail").value.trim().toLowerCase(),role=$("#inviteRole").value,btn=$("#inviteBtn");if(!email){$("#inviteMsg").textContent="Inserisci un indirizzo email.";return}btn.disabled=true;btn.textContent="Invio in corso…";$("#inviteMsg").textContent="";let {data,error}=await db.functions.invoke("invite-user",{body:{email,role}});btn.disabled=false;btn.textContent="Autorizza e invia invito";if(error){$("#inviteMsg").textContent=await edgeErrorMessage(error);return}if(!data||!data.ok){$("#inviteMsg").textContent=data&&data.error?data.error:"Non è stato possibile inviare l’invito.";return}$("#inviteEmail").value="";$("#inviteMsg").textContent="Invito inviato a "+email+". La persona deve aprire la mail e completare l’account.";await renderInvites()}
$("#loginBtn").addEventListener("click",login);$("#signupBtn").addEventListener("click",signup);$("#forgotBtn").addEventListener("click",()=>{let e=$("#authEmail").value.trim();$("#resetEmail").value=e;setAuthMode("forgot");setTimeout(()=>$("#resetEmail").focus(),50)});$("#sendResetBtn").addEventListener("click",forgotPassword);$("#forgotBackBtn").addEventListener("click",()=>setAuthMode("login"));$("#retryResetBtn").addEventListener("click",()=>setAuthMode("forgot"));$("#errorBackToLoginBtn").addEventListener("click",()=>setAuthMode("login"));$("#backToLoginBtn").addEventListener("click",()=>setAuthMode("login"));$("#savePasswordBtn").addEventListener("click",saveNewPassword);$("#showLoginBtn").addEventListener("click",()=>setAuthMode("login"));$("#completeInviteBtn").addEventListener("click",completeInvite);$("#activationToLoginBtn").addEventListener("click",()=>{let email=$("#activationEmail").textContent.trim();setAuthMode("login");$("#authEmail").value=email;$("#authPassword").value="";setTimeout(()=>$("#authPassword").focus(),50)});$("#inviteBtn").addEventListener("click",authorizeEmail);$("#addGroupBtn").addEventListener("click",addGroup);$("#logoutBtn").addEventListener("click",async()=>{if(bookingsChannel){db.removeChannel(bookingsChannel);bookingsChannel=null}if(notificationsChannel){db.removeChannel(notificationsChannel);notificationsChannel=null}await db.auth.signOut();currentUser=null;currentProfile=null;bookings=[];setAuthMode("login");showAuth("Disconnesso.")});
let recoveryFlow=false,inviteFlow=false,authBooted=false;
function hasAuthType(type){let u=authUrlSnapshot+" "+(window.location.hash||"")+" "+(window.location.search||"");return u.includes("type="+type)}
function isRecoveryUrl(){return hasAuthType("recovery")}
function isInviteUrl(){return hasAuthType("invite")}
if(isRecoveryUrl()){recoveryFlow=true;showAuth();setAuthMode("recovery")}else if(isInviteUrl()){inviteFlow=true;showAuth();setAuthMode("invite")}
db.auth.onAuthStateChange((event,session)=>{
  if(event==="PASSWORD_RECOVERY"){
    recoveryFlow=true;authBooted=true;showAuth();setAuthMode("recovery");return;
  }
  if(recoveryFlow||isRecoveryUrl()) return;
  if(inviteFlow||isInviteUrl()){
    inviteFlow=true;authBooted=true;showAuth();setAuthMode("invite");if(session)setTimeout(()=>prepareInviteMode(session),0);return;
  }
  if(event==="INITIAL_SESSION"){
    authBooted=true;
    if(session&&session.user)setTimeout(()=>enterApp(session.user),0);else showAuth();
  }
});
setTimeout(async()=>{if(recoveryFlow||isRecoveryUrl())return;if(inviteFlow||isInviteUrl()){let {data:{session}}=await db.auth.getSession();showAuth();setAuthMode("invite");if(session)await prepareInviteMode(session);else $("#authMsg").textContent="Il link di invito non è più valido. Chiedi all’amministratore un nuovo invito.";return}if(authBooted)return;let {data:{session}}=await db.auth.getSession();if(session&&session.user)await enterApp(session.user);else showAuth()},1200);
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");