const SUPABASE_URL="https://gfvwuzbwmvafcukadupo.supabase.co";
const SUPABASE_KEY="sb_publishable_dtc_AGtoapQyLTZe2TZ14Q_K3-21oSA";
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let currentUser=null,currentProfile=null;
const GROUPS=["KINDER (Inventafiabe)","KIDS","YOUNG 1 livello","YOUNG 2 livello","TEEN","TEEN OFF","1 ANNO","2 ANNO","3 ANNO","GARAGE 1","GARAGE 2","SCUDERIE","OFF 1","OFF 2","OFF 3","OFF 4","RIUNIONE DOCENTI KIDS","RIUNIONE DOCENTI ADULTI","RIUNIONE TUTTI","LABORATORI KIDS","WORKSHOP","FESTA","ALTRO"];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let bookings=JSON.parse(localStorage.getItem("vc_bookings_v2")||"[]"), news=JSON.parse(localStorage.getItem("vc_news_v2")||"[]"), cursor=new Date();
const save=()=>{localStorage.setItem("vc_bookings_v2",JSON.stringify(bookings));localStorage.setItem("vc_news_v2",JSON.stringify(news));renderAll()};
const iso=d=>{let x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}, mins=t=>{let[a,b]=t.split(":").map(Number);return a*60+b}, overlap=(a,b,c,d)=>mins(a)<mins(d)&&mins(c)<mins(b), fmt=d=>new Date(d+"T12:00").toLocaleDateString("it-IT",{weekday:"long",day:"numeric",month:"long"});
function go(id){$$(".view").forEach(v=>v.classList.remove("active"));$("#"+id).classList.add("active");if(id==="requests")renderRequests();if(id==="news")renderNews();window.scrollTo(0,0)}
$$("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go)); $("#bell").onclick=()=>go("news");
$("#group").innerHTML=GROUPS.map(x=>"<option>"+x+"</option>").join("");$("#group").onchange=e=>$("#otherWrap").hidden=e.target.value!=="ALTRO";$("#repeat").onchange=e=>$("#untilWrap").hidden=!e.target.checked;
function roomAvailability(){let date=$("#date").value,start=$("#start").value,end=$("#end").value,box=$("#roomChoices"),hint=$("#availabilityHint");if(!date||!start||!end||mins(end)<=mins(start)){box.innerHTML="";hint.textContent="Inserisci una data e una fascia oraria valida.";$("#room").value="";return}let rooms=["Sala Grande","Sala Piccola"],free=rooms.filter(r=>!bookings.some(b=>b.date===date&&b.room===r&&["approved","pending"].includes(b.status)&&overlap(b.start,b.end,start,end)));let choices=[];for(let r of rooms){let ok=free.includes(r);choices.push(`<button type="button" class="roomchoice ${ok?"free":"busy"}" data-room="${r}" ${ok?"":"disabled"}><b>${r.includes("Grande")?"🟠":"🟣"} ${r}</b><span>${ok?"LIBERA":"OCCUPATA / RICHIESTA"}</span></button>`)}if(free.length===2)choices.push(`<button type="button" class="roomchoice any" data-room="Una qualsiasi"><b>🎭 Una qualsiasi</b><span>Deciderà l’admin</span></button>`);box.innerHTML=choices.join("");hint.textContent=free.length?free.length===2?"Entrambe le sale sono disponibili.":"È disponibile una sola sala.":"Nessuna sala disponibile in questa fascia.";$("#room").value="";$$("[data-room]").forEach(b=>b.onclick=()=>{$$(".roomchoice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");$("#room").value=b.dataset.room})}
$("#date").addEventListener("change",roomAvailability);$("#start").addEventListener("change",roomAvailability);$("#end").addEventListener("change",roomAvailability);
function addNews(text){news.unshift({id:crypto.randomUUID(),text,at:new Date().toISOString(),read:false})}
function roomClass(r){return r.includes("Grande")?"grande":"piccola"} function dotClass(r){return r.includes("Grande")?"orange":"purple"}
function renderHome(){let t=iso(new Date());$("#todayDate").textContent=fmt(t);let arr=bookings.filter(b=>b.date===t&&b.status==="approved").sort((a,b)=>a.start.localeCompare(b.start));$("#todayRooms").innerHTML=["Sala Grande","Sala Piccola"].map(r=>{let a=arr.filter(b=>b.room===r);return '<div class="card roomline '+roomClass(r)+'"><b>'+r+'</b>'+(a.length?a.map(b=>'<div>'+b.start+'–'+b.end+' · '+b.group+(b.note?' — '+b.note:'')+'</div>').join(""):'<div class="muted">Libera oggi</div>')+'</div>'}).join("")}
function renderCalendar(){let y=cursor.getFullYear(),m=cursor.getMonth();$("#monthTitle").textContent=new Date(y,m,1).toLocaleDateString("it-IT",{month:"long",year:"numeric"});let first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),html="";for(let i=0;i<first;i++)html+='<div class="daycell empty"></div>';for(let d=1;d<=days;d++){let date=iso(new Date(y,m,d)),fs=$("#filterStart").value,fe=$("#filterEnd").value,arr=bookings.filter(b=>b.date===date&&["approved","pending"].includes(b.status)&&overlap(b.start,b.end,fs,fe));let dots=arr.map(b=>'<i class="dot '+dotClass(b.room)+' '+(b.status==="pending"?"pending":"")+'"></i>').join("");html+='<div class="daycell" data-date="'+date+'"><div class="daynum">'+d+'</div><div class="dots">'+dots+'</div></div>'}$("#monthGrid").innerHTML=html;$$(".daycell[data-date]").forEach(x=>x.onclick=()=>renderDay(x.dataset.date))}
function renderDay(date){go("day");$("#dayTitle").textContent=fmt(date);let a=bookings.filter(b=>b.date===date&&b.status!=="rejected").sort((x,y)=>x.start.localeCompare(y.start));$("#dayList").innerHTML=a.length?a.map(b=>'<div class="item roomline '+roomClass(b.room)+'"><b>'+b.start+'–'+b.end+' · '+b.room+'</b><div>'+b.group+'</div><small>'+b.actor+(b.note?' · '+b.note:'')+'</small><div><span class="tag '+(b.status==="pending"?"pending":"ok")+'">'+(b.status==="pending"?"IN ATTESA":"CONFERMATA")+'</span></div>'+(currentProfile&&currentProfile.role==="admin"?'<div class="actions"><button class="reject" data-del="'+b.id+'">🗑 Cancella'+(b.seriesId?' / serie':'')+'</button></div>':'')+'</div>').join(""):'<div class="card muted">Nessuna prenotazione.</div>';$("[data-del]").forEach(x=>x.onclick=()=>deleteBooking(x.dataset.del))}
function deleteBooking(id){let b=bookings.find(x=>x.id===id);if(!b)return;if(b.seriesId){openSeriesDelete(b);return}if(!confirm("Vuoi cancellare questa prenotazione?"))return;bookings=bookings.filter(x=>x.id!==id);addNews("Prenotazione cancellata: "+b.group+" · "+fmt(b.date)+" "+b.start+"–"+b.end);save();go("calendar")}
function openSeriesDelete(b){$("#seriesDeleteText").textContent=b.group+" · "+fmt(b.date)+" · "+b.start+"–"+b.end;$("#seriesDeleteModal").hidden=false;$("#deleteOne").onclick=()=>{bookings=bookings.filter(x=>x.id!==b.id);addNews("Data cancellata dalla serie: "+b.group+" · "+fmt(b.date));closeSeriesDelete();save();go("calendar")};$("#deleteSeries").onclick=()=>{bookings=bookings.filter(x=>x.seriesId!==b.seriesId);addNews("Serie cancellata: "+b.group+" · "+b.room);closeSeriesDelete();save();go("calendar")}}
function closeSeriesDelete(){$("#seriesDeleteModal").hidden=true}
$("#deleteCancel").onclick=closeSeriesDelete;
function renderRequests(){let a=bookings.filter(b=>b.status==="pending").sort((x,y)=>(x.date+x.start).localeCompare(y.date+y.start));let admin=currentProfile&&currentProfile.role==="admin";$("#requestList").innerHTML=a.length?a.map(b=>'<div class="item"><b>'+fmt(b.date)+'</b><div>'+b.start+'–'+b.end+' · '+b.room+'</div><div>'+b.group+'</div><small>Richiesta da '+b.actor+(b.note?' · '+b.note:'')+'</small>'+(admin?'<div class="actions"><button class="approve" data-a="'+b.id+'">✓ Approva</button><button class="reject" data-r="'+b.id+'">✕ Rifiuta</button></div>':'')+'</div>').join(""):'<div class="card muted">Nessuna richiesta in attesa.</div>';$("[data-a]").forEach(x=>x.onclick=()=>approve(x.dataset.a));$("[data-r]").forEach(x=>x.onclick=()=>reject(x.dataset.r))}
function approve(id){let b=bookings.find(x=>x.id===id);if(!b)return;let conflict=bookings.some(x=>x.id!==id&&x.date===b.date&&x.room===b.room&&x.status==="approved"&&overlap(x.start,x.end,b.start,b.end));if(conflict){alert("Attenzione: nel frattempo la sala risulta occupata in questa fascia.");return}b.status="approved";addNews("Richiesta approvata: "+b.room+" · "+fmt(b.date)+" "+b.start+"–"+b.end);save()}
function reject(id){let b=bookings.find(x=>x.id===id);if(!b)return;b.status="rejected";addNews("Richiesta rifiutata: "+b.room+" · "+fmt(b.date)+" "+b.start+"–"+b.end);save()}
function renderNews(){let a=news;$("#newsList").innerHTML=a.length?a.map(n=>'<div class="item">'+(!n.read?'<b>● NOVITÀ</b> ':'')+n.text+'<br><small>'+new Date(n.at).toLocaleString("it-IT")+'</small></div>').join(""):'<div class="card muted">Nessuna novità.</div>'}
$("#readAll").onclick=()=>{news.forEach(n=>n.read=true);save()};function badge(){let n=news.filter(x=>!x.read).length;$("#badge").textContent=n;$("#badge").dataset.zero=n?"0":"1"}
$("#bookForm").onsubmit=e=>{e.preventDefault();let actor=currentProfile.display_name||currentUser.email,role=currentProfile.role,room=$("#room").value,date=$("#date").value,start=$("#start").value,end=$("#end").value,group=$("#group").value==="ALTRO"?($("#other").value.trim()||"ALTRO"):$("#group").value,note=$("#note").value.trim();if(!date||mins(end)<=mins(start)){alert("Controlla data e orari.");return}if(!room){alert("Scegli una delle sale disponibili.");return}let recurring=$("#repeat").checked,until=$("#until").value;if(recurring&&role!=="admin"){alert("Le prenotazioni ricorrenti sono gestite dagli admin.");return}let dates=[date];if(recurring){if(!until||until<date){alert("Inserisci la data finale.");return}let d=new Date(date+"T12:00"),u=new Date(until+"T12:00");while((d=new Date(d.getTime()+7*86400000))<=u)dates.push(iso(d))}
let made=0,conf=[];for(let dt of dates){let collision=room!=="Una qualsiasi"&&bookings.some(b=>b.date===dt&&b.room===room&&["approved","pending"].includes(b.status)&&overlap(b.start,b.end,start,end));if(collision){conf.push(dt);continue}let status=(role==="admin"||recurring)?"approved":"pending";bookings.push({id:crypto.randomUUID(),seriesId:recurring?(dates[0]+"-"+actor+"-"+room):null,room,date:dt,start,end,group,note,actor,status});made++;if(status==="pending")addNews("Nuova richiesta di "+actor+": "+room+" · "+fmt(dt)+" "+start+"–"+end);else addNews("Nuova prenotazione: "+group+" · "+room+" · "+fmt(dt)+" "+start+"–"+end)}
save();$("#bookMsg").innerHTML='<div class="card"><b>'+(recurring?"Serie inserita":"Operazione registrata")+'</b><div>'+made+' data/e aggiunte'+(conf.length?' · '+conf.length+' conflitti saltati':'')+'.</div></div>';go(role==="admin"?"calendar":"requests")};
$("#prevMonth").onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);renderCalendar()};$("#nextMonth").onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);renderCalendar()};$("#filterStart").onchange=renderCalendar;$("#filterEnd").onchange=renderCalendar;
function renderAll(){renderHome();renderCalendar();renderRequests();badge();roomAvailability()}
async function enterApp(user){currentUser=user;let {data,error}=await db.from("profiles").select("id,display_name,role").eq("id",user.id).single();if(error||!data){$("#authMsg").textContent="Profilo non ancora disponibile. Riprova tra qualche secondo.";return}currentProfile=data;$("#authScreen").hidden=true;$("#appShell").hidden=false;$("#currentUser").textContent=(data.display_name||user.email)+" · "+(data.role==="admin"?"ADMIN":"OPERATORE");$("#roleInfo").innerHTML=data.role==="admin"?"Sei ADMIN: puoi inserire prenotazioni dirette e ricorrenti.":"Sei OPERATORE: le prenotazioni singole vengono inviate come richieste.";$("#repeat").closest("label").style.display=data.role==="admin"?"flex":"none";$("#adminAccessCard").hidden=data.role!=="admin";if(data.role!=="admin"){$("#repeat").checked=false;$("#untilWrap").hidden=true}else{await renderInvites()}$("#date").value=iso(new Date());renderAll()}
function showAuth(msg=""){$("#appShell").hidden=true;$("#authScreen").hidden=false;$("#authMsg").textContent=msg}
function setAuthMode(mode){$("#loginMode").hidden=mode!=="login";$("#signupMode").hidden=mode!=="signup";$("#authMsg").textContent=""}
async function login(){let email=$("#authEmail").value.trim(),password=$("#authPassword").value;if(!email||!password){showAuth("Inserisci email e password.");return}$("#authMsg").textContent="Accesso...";let {data,error}=await db.auth.signInWithPassword({email,password});if(error){showAuth(error.message);return}await enterApp(data.user)}
async function signup(){let name=$("#authName").value.trim(),email=$("#signupEmail").value.trim().toLowerCase(),password=$("#signupPassword").value;if(!name||!email||password.length<6){$("#authMsg").textContent="Inserisci nome, email e una password di almeno 6 caratteri.";return}$("#authMsg").textContent="Creazione account...";let {data,error}=await db.auth.signUp({email,password,options:{data:{name}}});if(error){$("#authMsg").textContent=error.message.includes("Database error")?"Questa email non è stata ancora autorizzata da un amministratore.":error.message;return}if(data.session&&data.user){await enterApp(data.user)}else{$("#authMsg").textContent="Account creato. Controlla la tua email e conferma l'indirizzo, poi torna qui e accedi.";setAuthMode("login")}}
async function renderInvites(){if(!currentProfile||currentProfile.role!=="admin")return;let {data}=await db.from("invitations").select("id,email,role,used_at,created_at").order("created_at",{ascending:false});$("#inviteList").innerHTML=(data||[]).map(i=>'<div class="inviteitem"><b>'+i.email+'</b><span>'+(i.role==="admin"?"ADMIN":"OPERATORE")+(i.used_at?" · ATTIVATO":" · AUTORIZZATO")+'</span></div>').join("")||'<div class="muted smallpad">Nessuna email autorizzata.</div>'}
async function authorizeEmail(){let email=$("#inviteEmail").value.trim().toLowerCase(),role=$("#inviteRole").value;if(!email){$("#inviteMsg").textContent="Inserisci un indirizzo email.";return}let {error}=await db.from("invitations").insert({email,role,invited_by:currentUser.id});if(error){$("#inviteMsg").textContent=error.code==="23505"?"Questa email è già autorizzata.":error.message;return}$("#inviteEmail").value="";$("#inviteMsg").textContent="Email autorizzata. Ora la persona può creare il proprio account.";await renderInvites()}
$("#loginBtn").onclick=login;$("#signupBtn").onclick=signup;$("#showSignupBtn").onclick=()=>setAuthMode("signup");$("#showLoginBtn").onclick=()=>setAuthMode("login");$("#inviteBtn").onclick=authorizeEmail;$("#logoutBtn").onclick=async()=>{await db.auth.signOut();currentUser=null;currentProfile=null;setAuthMode("login");showAuth("Disconnesso.")};
(async()=>{setAuthMode("login");let {data:{session}}=await db.auth.getSession();if(session&&session.user)await enterApp(session.user);else showAuth()})();
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");